<?php
    session_start();
if(isset($_SESSION['username'])){
        unset($_SESSION['username']);
        session_destroy();
        header("location:/project/admin/index.php");
}
else{
    header("location:/project/admin/index.php");
}
?>
